on:
  push:
     branches:
       - main


name: 🚀 Build and Deploy

jobs:
  blogdown:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master
       
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install rmarkdown, blogdown # might need knitr
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown"))'
       
      - name: Install hugo
        run: Rscript -e 'blogdown::install_hugo("0.80.0")'
 
      - name: Build site with blogdown
        run: Rscript -e "blogdown::build_site()"
      
      - name: Upload built
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
 
   deploy:
    runs-on: macOS-latest
    needs: blogdown
    steps:
      - name: Checkout
        uses: actions/checkout@master
 
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy..

  

