name: 🐦 Tweet
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@main
      - name: List all modified files
        run: |
          echo "Modified files:"
          echo "================"
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "- $file"
          done
      - name: Tweet it!
        uses: Eomm/why-don-t-you-tweet@v1.0.0
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        # with:
          # tweet-message: |
          #   Hello Reality Benders! This is a test tweet!
          # media_paths: |
          #   1st.png
          #   2nd.png

      - run: echo ${{ steps.tweet.outputs.response }}
