name: 🐦 Tweet
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        id: tweet
        uses: Eomm/why-don-t-you-tweet@v1
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          tweet-message: |
            Hello Reality Benders! This is a test automated tweet!
          # media_paths: |
          #   1st.png
          #   2nd.png

      - run: echo ${{ steps.tweet.outputs.response }}
